"""add_is_bot_to_chat

Revision ID: a6a78f93597c
Revises: 6781c0885257
Create Date: 2025-04-15 11:36:25.815799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a78f93597c'
down_revision: Union[str, None] = '6781c0885257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_bot', sa.String(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'is_bot')
    # ### end Alembic commands ###
